name = "git"
type = "webpack"
account_id = "d9c4a171c4a0d0a8e6f8204ae9ba0638"
workers_dev = true
zone_id = "cd7d068de3012345da9420df9514dad0"
webpack_config = "./packages/worker/webpack.config.js"
vars = {TOKEN="991047353:AAEwOd9vEYM9wQUR4tbcGgkbHpaIcUwxtWk"}
